"""Initial migration.

Revision ID: 237bc99775b3
Revises: 
Create Date: 2023-10-18 22:19:59.807364

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '237bc99775b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_on', sa.DateTime(), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])

    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_on', sa.DateTime(), nullable=False))
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_on', sa.DateTime(), nullable=False))
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('city_id',
               existing_type=mysql.INTEGER(unsigned=True),
               nullable=True)
        batch_op.drop_constraint('events_cities_id_fk', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_foreign_key('events_cities_id_fk', 'cities', ['city_id'], ['id'])
        batch_op.alter_column('city_id',
               existing_type=mysql.INTEGER(unsigned=True),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('created_on')

    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('created_on')

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('created_on')

    # ### end Alembic commands ###
